// <auto-generated />
using Consultorio_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultorio_Backend.Migrations
{
    [DbContext(typeof(ConsultorioDBContext))]
    [Migration("20231101054530_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Consultorio_Backend.Model.Asegurado", b =>
                {
                    b.Property<int>("id_asegurado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_asegurado"), 1L, 1);

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("id_seguro")
                        .HasColumnType("int");

                    b.Property<string>("nombre_del_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("id_asegurado");

                    b.HasIndex("id_seguro");

                    b.ToTable("asegurado");
                });

            modelBuilder.Entity("Consultorio_Backend.Model.Seguro", b =>
                {
                    b.Property<int>("id_seguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seguro"), 1L, 1);

                    b.Property<int>("codigo_seguro")
                        .HasColumnType("int");

                    b.Property<string>("nombre_del_seguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prima")
                        .HasColumnType("int");

                    b.Property<int>("suma_asegurada")
                        .HasColumnType("int");

                    b.HasKey("id_seguro");

                    b.ToTable("seguro");
                });

            modelBuilder.Entity("Consultorio_Backend.Model.Asegurado", b =>
                {
                    b.HasOne("Consultorio_Backend.Model.Seguro", "Seguro")
                        .WithMany()
                        .HasForeignKey("id_seguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguro");
                });
#pragma warning restore 612, 618
        }
    }
}
